language: android   # 声明构建语言环境

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置 false 吧
  email: false

sudo: false         # sudo 权限

android:            # 配置信息
  components:
    - tools
    - build-tools-29.0.0
    - android-29
    - extra-android-m2repository     # Android Support Repository
    - extra-android-support          # Support Library

before_install:
  - cd trail/app
  - chmod +x gradlew  # 改变 gradlew 的访问权限
  - gem install fir-cli

script:              # 执行:下面的命令
  - ./gradlew assembleRelease
#  - ./gradlew connectedAndroidTest
  - adb shell am instrument -w -r  \
    -e debug false -e class 'com.example.trail.MainActivityTest,com.example.trail.Calendar.CalendarFragmentTest,com.example.trail.Lists.ListsFragmentTest,com.example.trail.Lists.SideMenuActivityTest' \
    com.example.trail.test/androidx.test.runner.AndroidJUnitRunner

before_deploy:       # 部署之前
  # 使用 mv 命令进行修改 apk 文件的名字
  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/buff.apk

deploy:              # 部署
  provider: releases # 部署到 GitHub Release，除此之外，Travis CI 还支持发布到 fir.im、AWS、Google App Engine 等
  api_key:           # 填写 GitHub 的 token （Settings -> Personal access tokens -> Generate new token）
    secure: 7f4dc45a19f742dce39cbe4d1e5852xxxxxxxxx
  file: app/build/outputs/apk/buff.apk   # 部署文件路径
  skip_cleanup: true     # 设置为 true 以跳过清理,不然 apk 文件就会被清理
  on:     # 发布时机
    tags: true       # tags 设置为 true 表示只有在有 tag 的情况下才部署

after_deploy:
  - fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
